In [1]:
import numpy as ap

In [3]:
mx=ap.array(([1,1,1],[1,1,1],[1,1,1]))
mx

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
mx2=ap.ones((3,3),dtype=int)
mx2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
type(mx2)

numpy.ndarray

In [16]:
mx3=ap.zeros((7,8),dtype=int)
mx3.dtype


dtype('int32')

In [29]:
emptyL=ap.empty_like((5,3))
emptyL

array([         0, 1073741824])

In [31]:
empty=ap.empty((6,3))
empty

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306],
       [6.23053614e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.11261774e-306],
       [6.23037657e-307, 6.23053954e-307, 1.42419530e-306],
       [1.78021527e-306, 6.23059726e-307, 1.33511562e-306],
       [6.89805151e-307, 1.11261909e-306, 9.34609789e-307]])